#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : utf8proc
Version  : 2.7.0
Release  : 1
URL      : https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.7.0.tar.gz
Source0  : https://github.com/JuliaStrings/utf8proc/archive/refs/tags/v2.7.0.tar.gz
Summary  : UTF8 processing
Group    : Development/Tools
License  : MIT
Requires: utf8proc-lib = %{version}-%{release}
Requires: utf8proc-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
# utf8proc
[![CI](https://github.com/NanoComp/meep/actions/workflows/build-ci.yml/badge.svg)](https://github.com/JuliaStrings/utf8proc/actions/workflows/build-ci.yml)
[![AppVeyor status](https://ci.appveyor.com/api/projects/status/ivaa0v6ikxrmm5r6?svg=true)](https://ci.appveyor.com/project/StevenGJohnson/utf8proc)

%package dev
Summary: dev components for the utf8proc package.
Group: Development
Requires: utf8proc-lib = %{version}-%{release}
Provides: utf8proc-devel = %{version}-%{release}
Requires: utf8proc = %{version}-%{release}

%description dev
dev components for the utf8proc package.


%package lib
Summary: lib components for the utf8proc package.
Group: Libraries
Requires: utf8proc-license = %{version}-%{release}

%description lib
lib components for the utf8proc package.


%package license
Summary: license components for the utf8proc package.
Group: Default

%description license
license components for the utf8proc package.


%prep
%setup -q -n utf8proc-2.7.0
cd %{_builddir}/utf8proc-2.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650486866
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1650486866
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/utf8proc
cp %{_builddir}/utf8proc-2.7.0/LICENSE.md %{buildroot}/usr/share/package-licenses/utf8proc/3403915b023bebd3133b183aef3da09f0a3aa2ec
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/utf8proc.h
/usr/lib64/libutf8proc.so
/usr/lib64/pkgconfig/libutf8proc.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libutf8proc.so.2
/usr/lib64/libutf8proc.so.2.5.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/utf8proc/3403915b023bebd3133b183aef3da09f0a3aa2ec
